[tool.briefcase]
project_name = "app"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/app"
license = "BSD license"
author = 'Jane Developer'
author_email = "jane@example.com"

[tool.briefcase.app.app]
formal_name = "app"
description = "My first application"
icon = "src/app/resources/app"
sources = ['src/app']
requires = [
]


[tool.briefcase.app.app.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.app.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.app.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.app.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.app.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.app.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.app.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.app.web]
requires = [
    'toga-web>=0.3.0.dev38'
]
style_framework = "Bootstrap v4.6"
